from __future__ import annotations

from typing import Dict, List

# Orthographic vowel letters used by the syllable heuristic.
VOWELS = {"a", "e", "i", "o", "u", "y"}

# ARPAbet vowels used by alignment / fusion heuristics.
ARPA_VOWELS = {
    "aa",
    "ae",
    "ah",
    "ao",
    "aw",
    "ax",
    "eh",
    "er",
    "ay",
    "ey",
    "ih",
    "iy",
    "ow",
    "oy",
    "uh",
    "uw",
    "axr",
}

# Articulatory feature hints (therapy-facing; approximate for vowels).
PHONEME_FEATURES = {
    "p": {"place": "bilabial", "manner": "stop", "tongue": "bilabial", "voiced": False},
    "b": {"place": "bilabial", "manner": "stop", "tongue": "bilabial", "voiced": True},
    "t": {"place": "alveolar", "manner": "stop", "tongue": "alveolar", "voiced": False},
    "d": {"place": "alveolar", "manner": "stop", "tongue": "alveolar", "voiced": True},
    "k": {"place": "velar", "manner": "stop", "tongue": "velar", "voiced": False},
    "g": {"place": "velar", "manner": "stop", "tongue": "velar", "voiced": True},
    "s": {"place": "alveolar", "manner": "fricative", "tongue": "alveolar", "voiced": False},
    "z": {"place": "alveolar", "manner": "fricative", "tongue": "alveolar", "voiced": True},
    "f": {
        "place": "labiodental",
        "manner": "fricative",
        "tongue": "labiodental",
        "voiced": False,
    },
    "v": {
        "place": "labiodental",
        "manner": "fricative",
        "tongue": "labiodental",
        "voiced": True,
    },
    "th": {"place": "dental", "manner": "fricative", "tongue": "dental", "voiced": False},
    "dh": {"place": "dental", "manner": "fricative", "tongue": "dental", "voiced": True},
    "sh": {"place": "postalveolar", "manner": "fricative", "tongue": "postalveolar", "voiced": False},
    "ch": {"place": "postalveolar", "manner": "affricate", "tongue": "postalveolar", "voiced": False},
    "jh": {"place": "postalveolar", "manner": "affricate", "tongue": "postalveolar", "voiced": True},
    "zh": {"place": "postalveolar", "manner": "fricative", "tongue": "postalveolar", "voiced": True},
    "hh": {"place": "glottal", "manner": "fricative", "tongue": "glottal", "voiced": False},
    "r": {"place": "alveolar", "manner": "liquid", "tongue": "alveolar", "voiced": True},
    "l": {"place": "alveolar", "manner": "liquid", "tongue": "alveolar", "voiced": True},
    "w": {"place": "bilabial", "manner": "glide", "tongue": "bilabial", "voiced": True},
    "y": {"place": "palatal", "manner": "glide", "tongue": "palatal", "voiced": True},
    "m": {"place": "bilabial", "manner": "nasal", "tongue": "bilabial", "voiced": True},
    "n": {"place": "alveolar", "manner": "nasal", "tongue": "alveolar", "voiced": True},
    "ng": {"place": "velar", "manner": "nasal", "tongue": "velar", "voiced": True},
    # Vowels (approximate tongue region; useful for feedback when ASR swaps consonant↔vowel).
    "iy": {"place": "vowel", "manner": "vowel", "tongue": "front", "voiced": True},
    "ih": {"place": "vowel", "manner": "vowel", "tongue": "front", "voiced": True},
    "eh": {"place": "vowel", "manner": "vowel", "tongue": "front", "voiced": True},
    "ae": {"place": "vowel", "manner": "vowel", "tongue": "front", "voiced": True},
    "ey": {"place": "vowel", "manner": "vowel", "tongue": "front", "voiced": True},
    "ay": {"place": "vowel", "manner": "vowel", "tongue": "front", "voiced": True},
    "ah": {"place": "vowel", "manner": "vowel", "tongue": "central", "voiced": True},
    "ax": {"place": "vowel", "manner": "vowel", "tongue": "central", "voiced": True},
    "er": {"place": "vowel", "manner": "vowel", "tongue": "central", "voiced": True},
    "axr": {"place": "vowel", "manner": "vowel", "tongue": "central", "voiced": True},
    "aa": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
    "ao": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
    "ow": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
    "oy": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
    "uh": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
    "uw": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
    "aw": {"place": "vowel", "manner": "vowel", "tongue": "back", "voiced": True},
}

TONGUE_FEEDBACK = {
    "alveolar": "Place the tongue tip behind the upper front teeth.",
    "bilabial": "Use both lips together.",
    "labiodental": "Gently touch the upper teeth to the lower lip (e.g., for /f/ and /v/).",
    "dental": "Place the tongue tip lightly between the teeth (e.g., for /th/).",
    "velar": "Raise the back of the tongue toward the soft palate.",
    "palatal": "Raise the tongue toward the hard palate.",
    "postalveolar": "Curl the tongue slightly behind the alveolar ridge.",
    "glottal": "Keep the throat open and let air flow from the voice box (e.g., /h/).",
}

# IPA phones emitted by the tokenizer (after stripping stress) → ARPAbet-style tokens (g2p_en-like).
IPA_TO_ARPA: Dict[str, List[str]] = {
    "aɪ": ["ay"],
    "aɪə": ["ay", "ah"],
    "aɪɚ": ["ay", "er"],
    "aʊ": ["aw"],
    "b": ["b"],
    "d": ["d"],
    "dʒ": ["jh"],
    "eɪ": ["ey"],
    "f": ["f"],
    "h": ["hh"],
    "i": ["ih"],
    "iə": ["iy", "ah"],
    "iː": ["iy"],
    "j": ["y"],
    "k": ["k"],
    "l": ["l"],
    "m": ["m"],
    "n": ["n"],
    "n̩": ["n"],
    "oʊ": ["ow"],
    "p": ["p"],
    "r": ["r"],
    "s": ["s"],
    "t": ["t"],
    "tʃ": ["ch"],
    "uː": ["uw"],
    "v": ["v"],
    "w": ["w"],
    "x": ["hh"],
    "z": ["z"],
    "æ": ["ae"],
    "ð": ["dh"],
    "ŋ": ["ng"],
    "ɐ": ["ah"],
    "ɑː": ["aa"],
    "ɑːɹ": ["aa", "r"],
    "ɔ": ["ao"],
    "ɔɪ": ["oy"],
    "ɔː": ["ao"],
    "ɔːɹ": ["ao", "r"],
    "ə": ["ah"],
    "əl": ["ah", "l"],
    "ɚ": ["er"],
    "ɛ": ["eh"],
    "ɛɹ": ["eh", "r"],
    "ɜː": ["er"],
    "ɡ": ["g"],
    "ɪ": ["ih"],
    "ɪɹ": ["ih", "r"],
    "ɹ": ["r"],
    "ɾ": ["t"],
    "ʃ": ["sh"],
    "ʊ": ["uh"],
    "ʊɹ": ["uh", "r"],
    "ʌ": ["ah"],
    "ʒ": ["zh"],
    "ʔ": [],
    "θ": ["th"],
    "ᵻ": ["ih"],
}

